name: she_roams_bali
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10
  google_fonts: ^6.1.0
  http: ^1.1.0
  google_nav_bar: ^5.0.7
  carousel_slider: ^5.0.0 
  flutter_boxicons: ^3.2.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    
    - assets/images/Logo.svg

    - assets/images/background1.png
    - assets/images/SheRoam_background.webp
    - assets/slider/1.png
    - assets/slider/2.png
    - assets/slider/3.png